server:
  port: 8081
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/cloud-user
    username: root
    password: admin
  application:
    name: user-service
mybatis:
  type-aliases-package: xq.demo.pojo
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:10086/eureka